version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    ports:
      - 8002:80
    environment:
      YOURLS_SITE: https://example.com
      YOURLS_USER: example_username
      YOURLS_PASS: example_password
      YOURLS_DB_HOST: 127.0.0.1:3306
      YOURLS_DB_USER: root
      YOURLS_DB_PASS: 96PWF@an
      YOURLS_DB_NAME: yourls
