version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - /root/mysql/conf:/etc/mysql/conf.d
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/log:/data/logs
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone:ro

    logging:
      driver: "json-file"
      options:
         max-size: "2g"
         max-file: "10"


